# These are supported funding model platforms

open_collective: # Replace with a single Open Collective username
ko_fi: verzatiledev
custom: ['https://paypal.me/verzatileDev?country.x=EE&locale.x=en_US']
