title: Itch.io Handbook
description: A book about CSS & HTML for itch.io
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Contribute to the Github Repository: https://github.com/VerzatileDev/Itchio_HandBook
